# Generated by Django 4.1.7 on 2023-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("teacher", "Teacher"), ("student", "Student")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(null=True, upload_to="profile_images"),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("username", models.CharField(max_length=25, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("phone", models.BigIntegerField(null=True)),
                ("address", models.CharField(max_length=150, null=True)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science"),
                            ("ee", "Electrical"),
                            ("me", "Mechanical"),
                            ("electronics", "Electronics"),
                            ("ce", "Civil"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("github", models.CharField(max_length=150, null=True)),
                ("instagram", models.CharField(max_length=150, null=True)),
                ("twitter", models.CharField(max_length=150, null=True)),
                ("facebook", models.CharField(max_length=150, null=True)),
                ("auth_id", models.IntegerField(null=True)),
            ],
        ),
    ]
