# Generated by Django 4.1.7 on 2023-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="achievers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumb", models.ImageField(upload_to="Achievement Thumbnails")),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=2000)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="alumani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="faculty")),
                ("name", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=50)),
                ("text", models.CharField(max_length=100)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="carosuelImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="carosuelImages")),
                ("image_href", models.CharField(max_length=10)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="citinMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("href", models.CharField(max_length=100)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="documentsteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documenttitle",
                    models.CharField(
                        choices=[
                            ("consolidated-marksheet", "Consolidated Marksheet"),
                            ("provisional-degree", "Provisional Degree"),
                            ("duplicate-marksheet", "Duplicate Marksheet"),
                            ("migration-certificate", "Migration Certificate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("steps", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="faculty")),
                ("name", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=100)),
                ("link_facebook", models.CharField(max_length=50)),
                ("link_twitter", models.CharField(max_length=50)),
                ("link_skype", models.CharField(max_length=50)),
                ("link_linkdein", models.CharField(max_length=50)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="funFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student", models.IntegerField()),
                ("proudalumani", models.IntegerField()),
                ("placement", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="imggallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="image_gallery")),
                ("title", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("citcampus", "CIT Campus"),
                            ("labs", "Labs"),
                            ("hostel", "Hostel"),
                            ("workshop", "Workshop"),
                            ("tarunya", "Tarunya"),
                            ("lakshya", "Lakshya"),
                        ],
                        max_length=25,
                    ),
                ),
                ("thumbnail", models.BooleanField(default=False)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="importantNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("href", models.CharField(max_length=100)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internshipcreator", models.CharField(max_length=50)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science"),
                            ("ee", "Electrical"),
                            ("me", "Mechanical"),
                            ("electronics", "Electronics"),
                            ("ce", "Civil"),
                        ],
                        max_length=100,
                    ),
                ),
                ("jobtitle", models.CharField(max_length=50)),
                ("stipend", models.IntegerField()),
                ("url_internship", models.CharField(max_length=50)),
                ("jobdescription", models.CharField(max_length=5000)),
                ("jobimage", models.ImageField(upload_to="Internship Thumbnails")),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science"),
                            ("ee", "Electrical"),
                            ("me", "Mechanical"),
                            ("electronics", "Electronics"),
                            ("ce", "Civil"),
                        ],
                        max_length=25,
                    ),
                ),
                ("semester", models.IntegerField()),
                ("file", models.FileField(upload_to="notes")),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="seminar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seminarcreator", models.CharField(max_length=50)),
                (
                    "seminar_tag",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science"),
                            ("ee", "Electrical"),
                            ("me", "Mechanical"),
                            ("electronics", "Electronics"),
                            ("ce", "Civil"),
                        ],
                        max_length=50,
                    ),
                ),
                ("seminartitle", models.CharField(max_length=50)),
                ("seminardate", models.DateField()),
                ("duration", models.IntegerField()),
                ("seminarprice", models.IntegerField()),
                ("seminar_description", models.CharField(max_length=5000)),
                ("seminar_url", models.CharField(max_length=100)),
                ("seminarimage", models.ImageField(upload_to="Seminar Thumbnails")),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="topNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("href", models.CharField(max_length=100)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
    ]
