# Generated by Django 4.1.7 on 2023-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_alumani_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="eventsimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventimage", models.ImageField(upload_to="events")),
                ("show", models.BooleanField(default=True)),
            ],
        ),
    ]
