# Generated by Django 4.1.7 on 2023-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_eventsimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faculty",
            name="about",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="faculty"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="link_facebook",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="link_linkdein",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="link_skype",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="link_twitter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="show",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
