# Generated by Django 4.1.7 on 2023-06-20 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_faculty_username_alter_faculty_about_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faculty",
            old_name="link_skype",
            new_name="link_github",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="link_twitter",
            new_name="link_instagram",
        ),
    ]
