# Generated by Django 4.1.7 on 2023-06-20 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_rename_link_skype_faculty_link_github_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faculty",
            old_name="link_linkdein",
            new_name="link_twitter",
        ),
    ]
