# Generated by Django 4.1.7 on 2023-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rename_link_linkdein_faculty_link_twitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="about",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
