# Generated by Django 4.1.7 on 2023-06-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_faculty_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsteps",
            name="href",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
