# Generated by Django 4.1.7 on 2023-06-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_documentsteps_href"),
    ]

    operations = [
        migrations.CreateModel(
            name="bannernews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("show", models.BooleanField(default=True)),
            ],
        ),
    ]
