# Generated by Django 4.1.7 on 2023-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_bannernews"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannernews",
            name="href",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
